// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/service.proto
#ifndef GRPC_proto_2fservice_2eproto__INCLUDED
#define GRPC_proto_2fservice_2eproto__INCLUDED

#include "proto/service.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace proto {

class GameService final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.GameService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::proto::Packet, ::proto::Packet>> Tunnel(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::proto::Packet, ::proto::Packet>>(TunnelRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::proto::Packet, ::proto::Packet>> AsyncTunnel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::proto::Packet, ::proto::Packet>>(AsyncTunnelRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::proto::Packet, ::proto::Packet>* TunnelRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::proto::Packet, ::proto::Packet>* AsyncTunnelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::proto::Packet, ::proto::Packet>> Tunnel(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::proto::Packet, ::proto::Packet>>(TunnelRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::proto::Packet, ::proto::Packet>> AsyncTunnel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::proto::Packet, ::proto::Packet>>(AsyncTunnelRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::proto::Packet, ::proto::Packet>* TunnelRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::proto::Packet, ::proto::Packet>* AsyncTunnelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_Tunnel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Tunnel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::proto::Packet, ::proto::Packet>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Tunnel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Tunnel() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Tunnel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Tunnel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::proto::Packet, ::proto::Packet>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTunnel(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::proto::Packet, ::proto::Packet>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Tunnel<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Tunnel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Tunnel() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Tunnel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Tunnel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::proto::Packet, ::proto::Packet>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace proto


#endif  // GRPC_proto_2fservice_2eproto__INCLUDED
