/**
 * Copyright (C) 2011-2013 Yule Fox. All rights reserved.
 * http://www.yulefox.com/
 *
 * @file version.h
 * @author Fox (yulefox at gmail.com)
 * This file is autogenerated, do NOT edit it manually.
 */

#ifndef ELF_VERSION_H
#define ELF_VERSION_H

#include <elf/config.h>

#if defined(ELF_HAVE_PRAGMA_ONCE)
#   pragma once
#endif

/* @{ */
#define ELF_MAJOR_VERSION   0
#define ELF_MINOR_VERSION   1
#define ELF_PATCH_VERSION   0
#define ELF_BUILD_VERSION   282
#define ELF_VERSION_STR     "0.1.0(282)"
/* @} */

#endif /* !ELF_VERSION_H */
